### PR TITLE
Fixed enum34 dependency and moved requirements to setup.py

### PR DESCRIPTION
**Pull request by agronholm**
I tried my best to fix the Makefile too but it's still broken (Python 3 tests are not using a virtualenv for instance). Consider using tox instead.

### CODE REVIEW

**Comment by kislyuk** [comment]
Thanks! This looks good.

**Comment by agronholm** [comment]
Would you mind cutting a new patch release? I'll be needing it to install a project of mine. Thanks!

**Comment by kislyuk** [comment]
Sure thing. Released in v0.4.6, please test.

**Comment by agronholm** [comment]
Seems to install fine. Thank you.
Another question: is there a specific reason why it requires an older version of cryptography? Not judging, just wondering.

**Comment by kislyuk** [comment]
There is no specific reason. I just got into the habit of pinning major version ranges on my dependencies - at work we have been bitten by dependency drift enough times that we always pin them down completely and pip freeze the tree - but cryptography evolves fast enough that this approach may not work. If you run into an issue regarding this, I'm open to removing the upper bound.

**Comment by agronholm** [comment]
Thank you for the answer. I suspected this was the reason. FWIW, all the tests did pass when used with latest versions of all the dependencies.

**Pull request merged**
