### PR TITLE
Set reference URI parameter with enveloped method

### PR DESCRIPTION
**Pull request by leotada**
Set reference URI parameter with enveloped method if you provide. Before it was always empty string.

### CODE REVIEW

**Comment by kislyuk** [comment]
I'll have to think about this more, but the first thing to do is add tests that would fail before this change and succeed after it.

**Comment by kislyuk** [comment]
@leotada, can you please add tests?

**Comment by leotada** [comment]
How I do that? I run test.py im my pc have output:
OpenSSL.crypto.X509StoreContextError: [10, 1, 'certificate has expired']
signxml.InvalidCertificate: [10, 1, 'certificate has expired']
FAILED (errors=1)

**Comment by kislyuk** [comment]
Check the way Travis runs it. You should also be able to run the PR
yourself through Travis.

**Pull request closed without merging**
