### PR TITLE
Add anywhere flag to _find methods.

### PR DESCRIPTION
**Pull request by jmindek**
- Address Issue #32 Enveloped signature: Signature-placeholder not found when not
   direct child of root

### CODE REVIEW

**Comment by kislyuk** [comment]
Can you add a test case that exercises this functionality?

**Comment by kislyuk** [comment]
This expansion highlights the need to better guide users of this package to use best practices (make sure they pass a specific X.509 cert that they expect the signature to use, or another way to ascertain that the signature is authentic; and only trust data returned by `verify()`).

Since that concern is not really exacerbated by this change, and you seem to be in a rush, I can merge and release this now as long as you promise to add a test case in a later PR.

**Comment by jmindek** [comment]
I respect your desire to have a test case before merging and will add one
soon.

**Comment by kislyuk** [comment]
Merging now, will add a test case and release later today.

**Comment by jmindek** [comment]
Thanks Andrey.
I worked on adding a new method and xml file to test but just haven't had
the time to finish it up.

-Jerry

**Comment by kislyuk** [comment]
Released in v0.4.5. Please test.

**Pull request merged**
